# Generated by Django 3.0.6 on 2020-05-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ducks', '0003_auto_20200524_0339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'get_latest_by': 'id', 'ordering': ('recorddate',)},
        ),
    ]
