# Generated by Django 3.0.6 on 2020-05-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducks', '0004_auto_20200525_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='howmuch_food',
            field=models.CharField(help_text='For example: 4 oz, 10 pounds', max_length=100),
        ),
    ]
